lst = list()
first_val = int(input("Enter the first value : "))
lst.insert(0, first_val)
sec_val = int(input("Enter the second value : "))
lst.insert(1, sec_val)
third_val = int(input("Enter the third value : "))
lst.insert(2, third_val)
print(lst)
third_val_replace = int(input("Enter the replace for the third value: "))
lst.remove(third_val)
lst.append(third_val_replace)
fourth_val = int(input("Enter the next value : "))
lst.append(fourth_val)
fifth_val = int(input("Enter the next value : "))
lst.append(fifth_val)
sort_list = sorted(lst)
print("The sorted list : ", sort_list)
sort_list.pop(-1)
sort_list.reverse()
print(sort_list)
